
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.1'

target 'StaffRenter' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'rn-fetch-blob',
      :path => '../node_modules/rn-fetch-blob'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  #pod 'react-native-apple-sign-in', :path => "../node_modules/react-native-apple-sign-in/react-native-apple-sign-in.podspec"

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'


  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'




  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'StaffRenterTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#   use_flipper!({ 'Flipper-Folly' => '2.3.0' })
use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

#target 'nomnom-tvOS' do
  # Pods for NomNomVroom-tvOS

  #target 'nomnom-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end
#end
